services:
  frontend:
    build:
      context: ./
      dockerfile: frontend/frontend.dockerfile
    restart: always
    depends_on:
      - backend
    env_file: .env

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: true
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always

  celery_worker:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: true
    command: /app/worker-start.sh
    volumes:
      - ./backend:/app
      - user-data:/user-data
    restart: always
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file: .env

  proxy:
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - frontend

volumes:
  db-data:
  user-data:
