services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    image: d2s-app:dev
    platform: linux/x86_64
    command: yarn run dev --host 0.0.0.0 --port 8080
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_API_V1_STR=/api/v1
      - VITE_BRAND_FULL=Data to Science
      - VITE_BRAND_SHORT=D2S
      - VITE_BRAND_SLOGAN=A Data-driven Open Science Community for Sustained Innovation

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: true
    image: d2s-api:dev
    platform: linux/x86_64
    volumes:
      - ./backend:/app
      - external-data:/srv/external-data
      - log-data:/app/logs
      - tusd-data:/srv/tusd-data/data
      - user-data:/static
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend.env
      - db.env

  db:
    image: postgis/postgis:15-3.3
    platform: linux/x86_64
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=d2s
      - POSTGRES_DB=d2s
    env_file:
      - db.env

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/x86_64
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=youremail@example.com
      - PGADMIN_DEFAULT_PASSWORD=password

  redis:
    image: redis:alpine
    platform: linux/x86_64
    restart: always

  celery_worker:
    image: d2s-api:dev
    platform: linux/x86_64
    command: /app/celery/worker-start.sh
    volumes:
      - external-data:/srv/external-data
      - tusd-data:/srv/tusd-data/data
      - user-data:/static
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - backend.env
      - db.env

  celery_beat:
    image: d2s-api:dev
    platform: linux/x86_64
    command: /app/celery/beat-start.sh
    volumes:
      - celery-data:/var/run/celery
      - tusd-data:/srv/tusd-data/data
      - user-data:/static
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - backend.env
      - db.env

  flower:
    image: d2s-api:dev
    platform: linux/x86_64
    command: /app/celery/flower-start.sh
    volumes:
      - user-data:/user-data
    ports:
      - 5555:5555
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - backend.env
      - db.env

  proxy:
    build: 
      context: ./nginx
      dockerfile: nginx.dockerfile
      args:
        - DEFAULT_CONF=dev
    image: d2s-proxy:dev
    platform: linux/x86_64
    tmpfs:
      - /tmp
    ports:
      - "0.0.0.0:8000:80"
    restart: always
    depends_on:
      - frontend

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    volumes:
      - user-data:/static
    ports:
      - ":8888"
    environment:
      - PORT=8888
      - WORKERS_PER_CORE=1

  tusd:
    image: tusproject/tusd:latest
    command: -verbose -behind-proxy -hooks-http http://proxy/api/v1/tusd -hooks-http-forward-headers Cookie X-Project-ID X-Flight-ID X-Data-Type
    volumes:
      - ./tusd/hooks:/srv/tusd-hooks
      - tusd-data:/srv/tusd-data/data
      - user-data:/static
    restart: always
    depends_on:
      - frontend
      - backend
      - proxy

volumes:
  celery-data:
  db-data:
  log-data:
  user-data:
  tusd-data:
  external-data:
    driver: local
    driver_opts:
      type: none
      device: ${EXTERNAL_STORAGE}
      o: bind
